# Generated by Django 5.1.11 on 2025-08-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('image', models.ImageField(upload_to='alerts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
