# Generated by Django 5.1.11 on 2025-08-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_camera_user_delete_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserApp',
        ),
    ]
