# Generated by Django 5.1.11 on 2025-08-14 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_user_userapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApp',
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(default='0.0,0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='installed_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
