# Generated by Django 5.1.11 on 2025-08-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_userapp_camera_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
    ]
