# Generated by Django 5.1.11 on 2025-08-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera_id', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alerts/')),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
    ]
