# Generated by Django 5.1.11 on 2025-08-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
